---
version: '3.6'

services:

  mongodb-web:
    image: mongo:latest
    container_name: mongodb-web
    ports:
      - "27017:27017"
    expose: 
      - "27017"

  auth-service:
    container_name: auth-service
    restart: always
    build: ./auth
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    expose:
      - "3001"
    environment:
      - FASTIFY_PORT=3001
    volumes:
      - ./auth/:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongodb-web

  ticket-service:
    container_name: ticket-service
    restart: always
    build: ./tickets
    command: ["npm", "run", "dev"]
    ports:
      - "3002:3002"
    expose:
      - "3002"
    environment:
      - FASTIFY_PORT=3002
    volumes:
      - ./tickets/:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongodb-web

